"""add totp fields to user

Revision ID: 618188b0f4dd
Revises: 40dd59cfa21d
Create Date: 2026-03-20 20:32:52.151979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618188b0f4dd'
down_revision = '40dd59cfa21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('totp_enabled')

    # ### end Alembic commands ###
